[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.zip',
  'php82Extensions.dom',
  'php82Extensions.sockets',
  'php82Extensions.curl',
  'php82Extensions.fileinfo',
  'php82Extensions.tokenizer',
  'php82Extensions.xml',
  'php82Extensions.ctype',
  'php82Extensions.session'
]

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
  'npm install',
  'npm run build',
  'mkdir -p storage/framework/{sessions,views,cache,testing}',
  'mkdir -p storage/logs',
  'mkdir -p bootstrap/cache',
  'chmod -R 775 storage bootstrap/cache',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT'
